### ISSUE TITLE
Extension is not following PSR standards

### ISSUE THREAD

**Issue by dereuromark** [spryker-sdk/sdk#187]
https://github.com/spryker-sdk/sdk/blob/master/composer.json#L95

There are several violations here that need to get fixed:
https://github.com/spryker-sdk/sdk/tree/master/extension/Hello

-  src/ must contain PHP files
-  resources/ must contain config/yaml files etc, maybe config/ is OK if that is specific to that
- https://github.com/spryker-sdk/sdk/blob/master/extension/Hello/HelloBundle.php would then be /src/HelloBundle.php

Then proper PSR would be

    "Hello\\": "extension/Hello/src/"

**Comment by pavelmaksimov25** [comment]
@dereuromark Thank you for pointing out that. Bugfix - https://github.com/spryker-sdk/sdk/pull/193
