### ISSUE TITLE
Path in neon file

### ISSUE THREAD

**Issue by dereuromark** [spryker-sdk/sdk#194]
https://github.com/spryker-sdk/sdk/blob/master/composer.json#L106
should be 
```
paths:
    -  src/
```
in neon file instead

**Comment by pavelmaksimov25** [comment]
Thank you. I've created a bug https://spryker.atlassian.net/browse/SDK-924.

**Comment by pavelmaksimov25** [comment]
Fixed in [0.4.0](https://github.com/spryker-sdk/sdk/releases/tag/0.4.0) release.
