### ISSUE TITLE
SDK gets stuck right after asking for repo info

### ISSUE THREAD

**Issue by jaume-spryker** [spryker-sdk/sdk#276]
I am trying to set up (and test) the sdk.

I have followed this documentation and steps:

- https://docs.spryker.com/docs/sdk/dev/spryker-sdk.html#installation

I can use the sdk commands, but when trying to run **`spryker-sdk sdk:workflow:run`**  (previously I executed the **`spryker-sdk sdk:init:project --workflow=app`** ) it is getting stuck right after asking for the git repository.

The output I see on the logs is:
```{"message":"Unable` to read the file /project/composer.json: file_get_contents(/project/composer.json): Failed to open stream: No such file or directory","context":{},"level":400,"level_name":"ERROR","channel":"error_logger","datetime":"2022-11-14T15:13:37.967969+00:00","extra":{}}
{"message":"The command \"'git' 'remote' 'get-url' '--push' 'origin'\" failed.\n\nExit Code: 128(Invalid exit argument)\n\nWorking directory: /project\n\nOutput:\n================\n\n\nError Output:\n================\nfatal: not a git repository (or any parent up to mount point /)\nStopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).\n","context":{},"level":400,"level_name":"ERROR","channel":"error_logger","datetime":"2022-11-14T15:13:38.065658+00:00","extra":{}}```

**`composer.json`** file does exist, and I see no issues on permissions (can this be a race condition issue?).
When I try to run **`git remote get-url --push origin`** I get the correct ouptut (appTest.git), so I am not sure why the sdk is showing this error.

When trying to rerun the command, this is the error output on the terminal.

<img width="746" alt="Screenshot 2022-11-15 at 12 28 27" src="https://user-images.githubusercontent.com/117280664/201933169-12d87d5b-1dd3-42be-acbf-b02084a1de46.png">

Can someone point me in the right direction?

**Comment by vol4onok** [comment]
Tested can't reproduce. It seems like you generate PBC for an existing project as I see on the screenshot. 
It seems like you generate PBC for an existing project.
