### ISSUE TITLE
AddCrudFacade is not exists at Spryker SDK

### ISSUE THREAD

**Issue by alama-nfq** [spryker-sdk/sdk#312]
I'm trying to run AddCrud spryk but I can't find it in Spryker SDK
you can see that I'm using the latest version of it
<img width="989" alt="Screenshot 2023-01-04 at 5 43 43 PM" src="https://user-images.githubusercontent.com/119591958/210593067-b01e7338-54aa-48de-a761-4f84ffae352c.png">

**Comment by pavelmaksimov25** [comment]
Hi @alama-nfq. Thank you for the bug report.
We've fixed this issue in the https://github.com/spryker-sdk/sdk/releases/tag/0.6.9 release.
